server:
  port: 8888

# spring 的配置
spring:
  profiles:
    active: dev
  application:
    name:mybatis-plus-test
  devtools:
    restart:
      enabled: true
      exclude: static

logging:
  level:
    #根日志
    root: info
    #对应包下的日志级别
    com.pc.sz.mapper: trace
  pattern:
    # 日志格式
    console: '%p%m%n'