server:
  port: 8888

# spring 的配置
spring:
  profiles:
    active: local
  application:
    name:metainfo-backend
  devtools:
    restart:
      enabled: true
      exclude: static

logging:
  level:
    root: info