server:
  port: 8888

# spring 的配置
spring:
  profiles:
    active: local
  application:
    name:mybatis-plus-test
  devtools:
    restart:
      enabled: true
      exclude: static

logging:
  level:
    root: info
    com.pc.sz.mapper: trace

erp-url-info:
  erp-url: ${ERP_URL:https://10.132.20.23:9082}
  single-organization:
    api-path: /uapws/rest/service/dept
    headers: accessToken=${ERP_ACCESS_TOKEN:jjjjjjjk}